### ISSUE TITLE
Hi, jd best is amazing, and I wanna know more...

### ISSUE THREAD

**Issue by forrany** [heyimyunyl/jdconnect-core#2]
Just dance Best make it possible to play all songs in one version, that's really amzing!!

But I have a baned swtich, which can't connect to netwrok, so I want to build a local server to enjoy the 'jd best' in offline. So, is this repo that I can build in local, and How can I do it and set my switch(I have clone this repo, and run server.js in local, I just don't what to do next to make my just dance in switch to conncet the server )

**Comment by AleMMdev** [comment]
Hey there, I'm the developer of connect core's old version which yunyl has leaked it here. No you cannot use this in a banned switch and this isnt even jdbest servers. It requires a manual server setup also...
